pipeline {
    agent {
        node{
            label 'AGENT-1'
        }
    }
    environment {
        COURSE= "Jenkins"
    }
    stages {
        stage('Init') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds')
                        sh """
                            cd 00-vpc
                            terraform init
                        """
                }
                
            }
        }
        stage('Plan') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds')
                        sh """
                            cd 00-vpc
                            terraform Plan
                        """
                }
                
            }
        }
         stage('Deploy') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds')
                        sh """
                            cd 00-vpc
                            terraform apply -auto-approve
                        """
                }
                
            }
    }   stage('Trigger SG') {
            steps {
                script{
                    build job: '10-sg'
                        wait: false,
                        propagate: false
                }
                
            }
        }
          
    post {
         always {
            cleanWs() // Deletes the entire workspace
          }
         success {
                echo 'I will run if success'
         }
         failure{
               echo 'I will run if failure'
         }

        }
}