pipeline {
    agent {
        node{
            label 'AGENT-1'
        }
    }
    environment {
        COURSE= "Jenkins"
    }
    stages {
        stage('Init') {
            steps {
                script{
                     sh """
                        terraform init
                   """
                }
                
            }
        }
        stage('Plan') {
            steps {
                script{
                     sh """
                        terraform Plan
                   """
                }
                
            }
        }
         stage('Deploy') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }
            steps {
                script{
                     sh """
                        terraform apply -auto-approve
                   """
                }
                
            }
    }
    post {
         always {
            cleanWs() // Deletes the entire workspace
          }
         success {
                echo 'I will run if success'
         }
         failure{
               echo 'I will run if failure'
         }

        }
}