pipeline {
    agent {
        node{
            label 'AGENT-1'
        }
    }
    environment {
        COURSE= "Jenkins"
    }
    stages {
        stage('Init') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds')
                        sh """
                            cd 10-sg
                            terraform init
                        """
                }
                
            }
        }
        stage('Plan') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds')
                        sh """
                            cd 10-sg
                            terraform Plan
                        """
                }
                
            }
        }
         stage('Deploy') {
            
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds')
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                }
                
            }
    }  
     stage('Parellel Trigger') {
            Parellel {
                stage('Bastion'){
                    steps {
                    script{
                        build job: '20-bastion',
                            wait: false,
                            propagate: false
                        }
                    }

                    }
                stage('SG Rules'){
                    steps {
                    script{
                        build job: '20-bastion',
                            wait: false,
                            propagate: false
                        }
                    }

                    }
                    
            }
        }
          
    post {
         always {
            cleanWs() // Deletes the entire workspace
          }
         success {
                echo 'I will run if success'
         }
         failure{
               echo 'I will run if failure'
         }

        }
}